### PR TITLE
Unregister streams and callbacks when disconnected

### PR DESCRIPTION
**Pull request by lebauce**

### CODE REVIEW

**Comment by vtolstov** [comment]
looks good to me

**Comment by lebauce** [comment]
Could an other reviewer please take a look at this ? Thanks

**Comment by lebauce** [comment]
@berrange @trapgate @vrgakos Would is it be possible to review and merge this one if it's ok ? Thanks !

**Comment by trapgate** [comment]
Hey @lebauce, thank you for the PR. This is one of a few bugs that strongly suggest that we need to rework the way that go-libvirt handles events. The current support is limited to a small subset of the events supported by libvirt itself, and the way that event support was added to go-libvirt has made possible some subtle bugs where a client can deadlock the go-libvirt library simply by doing things in a different order. We're in the midst of reworking the rpc code, and I'll make sure that we get the result of your change even though the implementation will be different.

**Comment by benlemasurier** [comment]
resolved by #113

**Pull request closed without merging**
