### PR TITLE
Add Secrets()

### PR DESCRIPTION
**Pull request by benlemasurier**
This adds the `Secrets()` method, used to retrieve all secrets managed by the libvirt daemon.

### CODE REVIEW

**Comment by mdlayher** [comment]
Slight naming nitpick: prefix new constants with SecretUsageType instead of just SecretUsage.

Otherwise LGTM.

**Comment by benlemasurier** [comment]
> Slight naming nitpick: prefix new constants with SecretUsageType instead of just SecretUsage.

:white_check_mark:

**Comment by mdlayher** [comment]
LGTM

**Comment by benlemasurier** [comment]
review seems to be unsatisfied, mind approving?

**Comment by mdlayher** [comment]
Done.

**Pull request merged**
