### PR TITLE
Add ProcDomainStats procedure #WIP (#40)

### PR DESCRIPTION
**Pull request by amandahla**
This is a draft for issue #40 

I need help to understand how to decode the XDR. :-( 
Please, anyone?

I put the file DomainStats.pcap that I'm using on diretory 'scripts'. 

The reply is something like:
retStats -> 
	retStats[] -> 
		dom
		params[] ->
			field
			i (or ul or s...)

### CODE REVIEW

**Comment by mdlayher** [comment]
Leaving for @benlemasurier since he's the libvirt XDR RPC expert.

**Comment by benlemasurier** [comment]
@amandahla I highly recommend you build libvirt's dissector plugin for wireshark. With the plugin you'll be able to decode and view RPC communication on the wire.

**Comment by amandahla** [comment]
@benlemasurier Thanks! I'm already using. The problem is that I don't know how to deal with this structure. Especially because the last field can be number, string ...This is why I asked for help/suggestions :-)

This is what I get:
libvirt

I try use interface type for last field but it didnt work with go-xdr

**Comment by trapgate** [comment]
Closing this because we now have this function in the generated code: ConnectGetAllDomainStats().

**Pull request closed without merging**
