### PR TITLE
WIP: Make libvirtError public and add Code and Domain consts

### LINKED ISSUE #121: Make error public, to allow more fine grained control for clients
This issue is a followup from: https://github.com/digitalocean/go-libvirt/issues/56

We are evaluating to use `go-libvirt` library in the upstream https://github.com/dmacvicar/terraform-provider-libvirt/pull/813

Right now, not having acess to specific error is problematic, since we leveraged these errors with the other `libvirt` golang 
library. see 

Is any chance to expose this errors? What is the valid rationale? we would be able to help to improve the library if needed.

I still agree also with @rmohr https://github.com/digitalocean/go-libvirt/issues/56#issuecomment-356212381

see for example:

https://github.com/dmacvicar/terraform-provider-libvirt/blob/master/libvirt/volume.go#L22

### PR DESCRIPTION
**Pull request by kskewes**
Closes #121 #56 

Resurrection of PR #57 

---- Original Commit Message ----
In order to allow fine-grained error handling:
 * change libvirtError to LibvirtError and implement the error interface.
 * extract Code and DomainID constants from libvirt sources

Signed-off-by: Roman Mohr <rmohr@redhat.com>
---- End ----

### CODE REVIEW

**Comment by kskewes** [comment]
Given the number of commits and the addition of an error handling case `IsNotFound` and related consts I think it's easier to start fresh rather than from the original PR. Closing.

**Comment by MalloZup** [comment]
nice @kskewes  that you started working on this that is great.

**Comment by MalloZup** [comment]
I was about to initiate also a PR but since you took the ownership on the old pr I will let you continue working on this. :flower_playing_cards:

**Comment by kskewes** [comment]
Thank you but by all means please go ahead.
I had a look but I think it's better to start fresh given the activity over past two years since the previous PR.

**Pull request closed without merging**
